### PR TITLE
fix (docs): cosmetics

### PR DESCRIPTION
**Pull request by loicjaouen**
Cosmetics on the documentation for regular users to not try to install requirements when pip install is all they need

### CODE REVIEW

**Comment by loicjaouen** [comment]
used the very nice makefile install requirements, build the docs and try them out

**Comment by loicjaouen** [comment]
I can add a few lines about the Makefile if you wish

**Review by subotic — APPROVED** [review]
Great, thanks! LGTM

**Comment by subotic** [comment]
> I can add a few lines about the Makefile if you wish

That would be great. Thanks!

**Comment by musicEnfanthen** [comment]
@subotic Why is the integration test failing when @loicjaouen only changed the `README.md` ? 

There is an option to exclude changes to `.md` files in the gh action:

```
on:
    push:
        branches:
            - '**'
        paths-ignore:
            - '**.md' # ignore changes in markdown files
```

Question remains why checks have failed at all?

**Comment by subotic** [comment]
because they are failing on `main`

**Comment by subotic** [comment]
Github doesn't allow me to merge `main` into this branch in this PR view. Loïc, could you please merge `main` locally into this branch and then push it? The tests are fixed in the meantime on `main`.

**Comment by subotic** [comment]
ok, I changed some settings. now I could merge `main` into this branch.

**Comment by subotic** [comment]
tests are passing now :-)

**Comment by loicjaouen** [comment]
sorry, I missed the exchange, let me just add a couple of lines for the make file and merge (I started to change the make file a bit but I might do that later)

**Comment by loicjaouen** [comment]
here I am, I already pushed to github pages, but that can easily be undone if needed, I don't have more to add for now.

is it still fine to merge @subotic ?

**Comment by subotic** [comment]
ok, I will merge it then.

**Pull request merged**
