### PR TITLE
refactor(xmlupload): implement rustworkx.PyDiGraph.filter_nodes in function _remove_leaf_nodes (DEV-2838)

### PR DESCRIPTION
**Pull request by Nora-Olivia-Ammann**

### CODE REVIEW

**Comment by Nora-Olivia-Ammann** [comment]
The rustworkx function added here is not yet released. It is expected to be in 0.14

**Comment by jnussbaum** [comment]
@Nora-Olivia-Ammann Can we close this PR? It will still be stored in the deleted PRs, so that you can come back to it when the new release is out.

**Comment by Nora-Olivia-Ammann** [comment]
> @Nora-Olivia-Ammann Can we close this PR? It will still be stored in the deleted PRs, so that you can come back to it when the new release is out.

There is a function in the code that could be replaced by a rustworkx functionality. It is already in the documentation but not in the released version. My intention was to replace the list comprehension (which is not efficient) with the new function as soon as the new version is released, which based on past frequencies should be within the next month. Would you prefer to reopen a new PR once the new version is released?

**Comment by jnussbaum** [comment]
> > @Nora-Olivia-Ammann Can we close this PR? It will still be stored in the deleted PRs, so that you can come back to it when the new release is out.
> 
> There is a function in the code that could be replaced by a rustworkx functionality. It is already in the documentation but not in the released version. My intention was to replace the list comprehension (which is not efficient) with the new function as soon as the new version is released, which based on past frequencies should be within the next month. Would you prefer to reopen a new PR once the new version is released?

I thought you could close it, and reopen when the release happened (and when we bumped our dependencies). I just thought it's annoying to have too many open PRs.

**Pull request closed without merging**
